# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc268478da11bf885f71cc746e2a7f0dc720cf4d9ada419d0743cec6b7d6f93f12a2bd5ce826fc21a57e68f4f28f69d7fcf910f67a6dfeda898c07909342e127

test:
  secret_key_base: 8b1ec5be202eea9b602e5ed13f84b32e3ca01d14b7b0ecb2bb14c7d93e3db57e102d2c072f6c47efafac28ecc40ddcaa14c7c74beffb3381c4573732ce7412cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
